### ISSUE TITLE
이벤트 발생 조건 구체화

### ISSUE THREAD

**Issue by seong0929** [Tiny-Metro/Tiny-Metro#100]
- [이벤트](https://github.com/Tiny-Metro/Tiny-Metro/wiki/Document:-%EC%9D%B4%EB%B2%A4%ED%8A%B8): 이벤트 발생 조건이 없음

**Comment by cstrnull00** [comment]
[이벤트](https://github.com/Tiny-Metro/Tiny-Metro/wiki/Document:-%EC%9D%B4%EB%B2%A4%ED%8A%B8#%EC%9D%B4%EB%B2%A4%ED%8A%B8) 탭에 정리
