### ISSUE TITLE
겹치는 노선 표시 방법

### ISSUE THREAD

**Issue by KimDa99** [Tiny-Metro/Tiny-Metro#102]
![image](https://user-images.githubusercontent.com/91198933/211722985-d6152b0f-4aa8-48d9-8d5b-be72ee558184.png)

A)노선들이 같은 방향으로 뻗어있고, 한 노선이 중간에 꺾일 때, 화면에 어떻게 표시되어야 하는가
1번 or 2번?

B)그리고 3번같은 상황이 발생될 수 있나? 역1, 역2, 역3이 일직선으로 순서대로 놓여져 있을때, 노선 A는 역1, 역2를 통과하고, 노선B는 역1, 역3만 통과한다(역2는 통과 x).

**Comment by seong0929** [comment]
A) 1번처럼 표시됩니다.
B) 3번 가능합니다.
