### ISSUE TITLE
튜토리얼 시안 및 멘트

### ISSUE THREAD

**Issue by AzureSoda** [Tiny-Metro/Tiny-Metro#111]
튜토리얼 멘트, 스크립트

https://docs.google.com/presentation/d/1ftOmoFviXLHsuMxAtYSJjw5drANkWlgnygVqEA9mw8w/edit?usp=sharing

▶안녕하세요 Tiny-Metro의 세상에 오신 것을 환영합니다.
당신은 이곳에서 역 사이에 노선을 만들어 기차를 운행하고 은행과 정책을 효율적으로 사용하여 지하철을 더 키워 나갈 수 있습니다. 최대한 많은 사람을 만족시키면서 지하철을 확장해 나가보세요!

▶차근차근 안내할게요. 우선 노선부터 그려볼까요?

[유저가 노선을 그림]

▶잘 했어요. 노선을 그려 역 사이를 개통할 수 있어요.
현재 사용할 수 있는 노선과 사용할 수 없는 노선은 오른쪽에서 볼 수 있어요.

▶이번엔 열차를 클릭해 볼까요?

[열차를 클릭]

▶열차를 클릭해서 열차에 대한 정보를 볼 수 있고 열차를 업그레이드시킬 수 있어요

▶다시 게임 진행 화면으로 넘어가 볼까요?

[역에 승객 추가]

▶저기 승객이 보이네요.
승객은 각자 모양에 맞는 역으로 가야해요.

▶승객이 원하는 곳에 가지 못하면 불만도가 쌓이게 돼요.
불만도가 쌓이면 게임오버가 돼요. 

[동그라미 역 새로 생성]

▶역이 하나 생겼네요 새로 생긴 역을 이어볼까요?

[노선을 새로 생긴 역과 연결]

▶잘 했어요! 역을 클릭해서 역에 대한 정보도 알 수 있어요

▶그런데 주어진 노선을 다 써버렸어요. 상점 아이콘을 클릭해 볼까요?

[상점 아이콘 주변 반짝이는 사각형 강조 효과->클릭]

[상점 팝업 창 생성]

▶상점에서 노선을 구매해 볼까요?
 
[상점에서 노선 구매]

▶다시 게임플레이 화면으로 나가볼게요

[게임플레이 화면으로 이동]

▶좋아요! 이렇게 상점에서는 게임진행에 필요한 여러 물품들을 구매할 수 있어요!

▶그런데 돈을 다 써버리셨군요! Tiny-metro에서는 돈을 사용하여 상점에서 물품을 구매하거나 기차를 업그레이드할 수 있어요

▶돈이 필요하다면 은행에서 대출받을 수 있답니다.

[은행 아이콘 주변 반짝이는 사각형 강조 효과 -> 클릭]

[은행 팝업 창 생성] 

▶은행에서 돈을 대출받을 수 있어요.
단계 별로 대출받을 수 있는 금액이 다르며 게임 진행 상황에 따라 해금이 돼요.

▶돈이 마이너스인 상태에서 시간이 지나가면 게임오버가 되니 주의해야해요!

▶이번엔 돈을 많이 얻을 수 있는 투자 받을 수 있는 방법에 대해서 알려드릴게요!
오른쪽 상단의 투자받기 버튼을 보세요

[투자받기 아이콘 주변 반짝이는 사각형 강조 효과]

▶1주일마다 새로운 투자 미션이 생성되며 최대 3개까지 투자미션을 가질 수 있어요.
⟳버튼을 눌러 미션을 갱신할 수 있어요.
투자를 통해 많은 돈을 얻을 수 있지만 미션 실패 시 돈을 배상해야 해요.

▶이번에는 정책에 대해서 알아볼까요?
게임플레이 화면으로 이동해주세요.

[게임플레이 화면으로 이동]

▶Tiny-Metro의 세상에서는 정책도 사용할 수 있어요!
아래 정책 아이콘을 클릭해 볼까요? 

[정책 아이콘 주변 반짝이는 사각형 강조 효과->클릭]

[정책 팝업 창 생성]

▶정책을 통해 불만도와 같은 승객들의 태도를 크게 바꿀 수 있어요.

[튜토리얼 플레이 중 
게임 시간 14일이 되기 전까지는 유저 스스로 플레이하게 둔다.]

[튜토리얼 플레이 중 게임 시간 14일이 지난 경우]

[이벤트 창 주변 반짝이는 사각형 강조 효과]

▶잠깐! Tiny-Metro에서의 시간이 14일이 지나면 이벤트가 생기게 돼요. 이벤트는 일정기간 동안 유지되고 게임의 판도를 크게 바꿀 수 있어요!
위 이벤트 창을 클릭하면 이벤트의 내용을 확인할 수 있어요

▶ 좋아요! 튜토리얼은 여기까지입니다.
이제 본격적으로 즐겁게 Tiny-Metro를 플레이 해주세요!

**Comment by AzureSoda** [comment]
튜토리얼 멘트, 스크립트
▶안녕하세요 Tiny-Metro의 세상에 오신 것을 환영합니다.
당신은 이곳에서 역 사이에 노선을 만들어 기차를 운행하고 은행과 정책을 효율적으로 사용하여 지하철을 더 키워 나갈 수 있습니다. 최대한 많은 사람을 만족시키면서 지하철을 확장해 나가보세요!

▶차근차근 안내할게요. 우선 노선부터 그려볼까요?

[유저가 노선을 그림]

▶잘 했어요. 노선을 그려 역 사이를 개통할 수 있어요.
현재 사용할 수 있는 노선과 사용할 수 없는 노선은 오른쪽에서 볼 수 있어요.

▶이번엔 열차를 클릭해 볼까요?

[열차를 클릭]

▶열차를 클릭해서 열차에 대한 정보를 볼 수 있고 열차를 업그레이드시킬 수 있어요

▶다시 게임 진행 화면으로 넘어가 볼까요?

[역에 승객 추가]

▶저기 승객이 보이네요.
승객은 각자 모양에 맞는 역으로 가야해요.

▶승객이 원하는 곳에 가지 못하면 불만도가 쌓이게 돼요.
불만도가 쌓이면 게임오버가 돼요. 

[동그라미 역 새로 생성]

▶역이 하나 생겼네요 새로 생긴 역을 이어볼까요?

[노선을 새로 생긴 역과 연결]

잘 했어요! 역을 클릭해서 역에 대한 정보도 알 수 있어요

그런데 주어진 노선을 다 써버렸어요. 상점 아이콘을 클릭해 볼까요?

[상점 아이콘 주변 반짝이는 사각형 강조 효과->클릭]

[상점 팝업 창 생성]

▶상점에서 노선을 구매해 볼까요?
 
[상점에서 노선 구매]

▶다시 게임플레이 화면으로 나가볼게요

[게임플레이 화면으로 이동]

▶좋아요! 이렇게 상점에서는 게임진행에 필요한 여러 물품들을 구매할 수 있어요!

▶그런데 돈을 다 써버리셨군요! Tiny-metro에서는 돈을 사용하여 상점에서 물품을 구매하거나 기차를 업그레이드할 수 있어요

▶돈이 필요하다면 은행에서 대출받을 수 있답니다.

[은행 아이콘 주변 반짝이는 사각형 강조 효과 -> 클릭]

[은행 팝업 창 생성] 

▶은행에서 돈을 대출받을 수 있어요.
단계 별로 대출받을 수 있는 금액이 다르며 게임 진행 상황에 따라 해금이 돼요.

▶돈이 마이너스인 상태에서 시간이 지나가면 게임오버가 되니 주의해야해요!

▶이번엔 돈을 많이 얻을 수 있는 투자 받을 수 있는 방법에 대해서 알려드릴게요!
오른쪽 상단의 투자받기 버튼을 보세요

[투자받기 아이콘 주변 반짝이는 사각형 강조 효과]

▶1주일마다 새로운 투자 미션이 생성되며 최대 3개까지 투자미션을 가질 수 있어요.
⟳버튼을 눌러 미션을 갱신할 수 있어요.
투자를 통해 많은 돈을 얻을 수 있지만 미션 실패 시 돈을 배상해야 해요.

▶이번에는 정책에 대해서 알아볼까요?
게임플레이 화면으로 이동해주세요.

[게임플레이 화면으로 이동]

▶Tiny-Metro의 세상에서는 정책도 사용할 수 있어요!
아래 정책 아이콘을 클릭해 볼까요? 

[정책 아이콘 주변 반짝이는 사각형 강조 효과->클릭]

[정책 팝업 창 생성]

▶정책을 통해 불만도와 같은 승객들의 태도를 크게 바꿀 수 있어요.

[튜토리얼 플레이 중 
게임 시간 14일이 되기 전까지는 유저 스스로 플레이하게 둔다.]

[튜토리얼 플레이 중 게임 시간 14일이 지난 경우]

[이벤트 창 주변 반짝이는 사각형 강조 효과]

▶잠깐! Tiny-Metro에서의 시간이 14일이 지나면 이벤트가 생기게 돼요. 이벤트는 일정기간 동안 유지되고 게임의 판도를 크게 바꿀 수 있어요!
위 이벤트 창을 클릭하면 이벤트의 내용을 확인할 수 있어요

▶ 좋아요! 튜토리얼은 여기까지입니다.
이제 본격적으로 즐겁게 Tiny-Metro를 플레이 해주세요!

**Comment by seong0929** [comment]
[대체제](https://github.com/Tiny-Metro/Tiny-Metro/issues/117)
