### ISSUE TITLE
튜토리얼 멘트 정중한 버전

### ISSUE THREAD

**Issue by AzureSoda** [Tiny-Metro/Tiny-Metro#117]
<h2>튜토리얼 멘트 정중한 버전+피드백 반영 (객차에 대한 설명, 상점에 대한 설명 수정, 멘트를 자연스럽게 수정) 입니다.  </h2>
<hr>

[튜토리얼 처음부터 호출]

안녕하세요 Poly-Metro의 세계에 오신 것을 환영합니다. 이곳에서는 전철 노선을 설계하여 승객들을 목적지까지 안내할 수 있습니다. 지하철을 확장하며 최대한 많은 사람들을 만족시켜 보세요.

차근차근 안내하겠습니다. 역에 승객이 등장했습니다.
승객들은 자신과 같은 모양의 역에 하차해야 합니다.

먼저 세모 역과 동그라미역을 차례로 클릭해서 노선을 그려보세요

잘 했습니다. 역과 역을 클릭해서 노선을 개통할 수 있습니다. 

열차는 왕복으로 노선을 운행하고, 승객들은 자동으로 승하차합니다. 
승객은 탑승 시 요금을 지불합니다

노선 끝의 핸들을 클릭한 뒤, 다른 역을 클릭하여 노선을 연장할 수 있습니다. 새로 생긴 역을 기존 노선과 연결해 보세요.

게임이 진행되면서 시간이 흐르면 역 후보지가 생성됩니다. 새로운 노선을 만들거나 기존 노선을 연장해 승객들을 목적지로 안내하세요.

이번에는 불만도에 대해서 알아보겠습니다.
역 후보지를 도시철도망에 연결해주지 않으면 불만도가 쌓입니다. 만약 불만도가 지나치게 높아진다면 게임이 종료됩니다.

대기 중인 승객이 많아질수록 역의 불만도가 증가합니다. 승객들이 전철에 탑승할 때마다 불만도가 감소합니다.
Poly-Metro에서는 다양한 지형이 존재합니다. 그 중에서 강을 건너려면 다리가, 산을 통과하려면 터널이 필요합니다.

강 넘어 새로 생긴 역에 노선을 연결하여 다리를 사용해 보겠습니다.
세모 역을 새로 생긴 역에 연결해 보세요

잘 하셨습니다. 새로운 노선을 성공적으로 사용하였습니다.
현재 사용할 수 있는 노선과 사용할 수 없는 노선은 오른쪽에서 볼 수 있습니다

이제 산을 넘어 노선을 연결해 보겠습니다. 별 역을 새로 생긴 역에 터널을 사용하여 연결해 주세요.

잘 하셨습니다. 다리와 터널은 상점에서 구매할 수 있습니다. 
그럼 이제 상점에 대해 알아볼 차례입니다. 하단에 위치한 상점 아이콘을 클릭해 주세요.

상점에서 객차를 한번 구매해 보겠습니다. 아래 상점 창에서 구매 과정을 진행해 주세요.

움직이는 열차 뒤에 객차를 연결하면, 노선을 따라 이동하는 열차에 승객 수를 늘릴 수 있습니다.
방금 구매한 객차를 열차뒤에 연결해 보세요.

이처럼 상점에서는 게임진행에 필요한 다양한 아이템들을 구매할 수 있습니다

이번엔 역에 대해서 알아보겠습니다.

역을 클릭하면 역에 대한 정보를 확인할 수 있습니다.

또한 역을 업그레이드하면 역의 수용인원을 늘릴 수 있습니다. 

열차를 클릭하면 열차에 관한 정보를 확인할 수 있습니다.
업그레이드하면 열차의 속도를 높이고, 더 많은 승객을 태울 수 있습니다.
열차를 따라가는 객차를 업그레이드하면 더 많은 승객을 태울 수 있습니다.

직접 업그레이드 버튼을 눌러서 열차를 업그레이드시켜보세요

매주 마지막 날에는 운영비가 지출되며, 재정이 마이너스 상태로 지속되면 결국 파산할 수 있습니다.

돈이 필요할 경우 은행에서 대출을 받을 수 있습니다. 이제 은행에 대해 알아볼 차례입니다. 하단의 은행 아이콘을 클릭해 주세요.

은행을 통해 대출을 받을 수 있으며, 각 단계별로 대출 가능한 금액이 다릅니다. 게임 진행 상황에 따라 대출 옵션이 해금됩니다.

잔고가 마이너스 상태로 오랫동안 지속되면 게임오버가 되므로 주의하세요.

이제 투자를 받아 돈을 얻는 방법에 대해 알려드리겠습니다.

오른쪽 상단의 '투자받기' 버튼을 클릭해 보세요. 매주 새로운 투자 미션이 생성되며, 최대 3개의 투자 미션을 가질 수 있습니다.
⟳버튼을 눌러 미션을 갱신할 수 있습니다

투자를 통해 큰 금액을 얻을 수 있지만, 미션에 실패하면 배상해야 하므로 주의하세요.
이제 게임 플레이 화면으로 돌아갑시다. 모든 창을 닫아 주세요.
Tiny-Metro의 세계에서는 정책을 사용할 수 있습니다. 아래 정책 아이콘을 클릭해 보세요.
정책을 통해 승객들의 불만도와 운영비를 조정할 수 있습니다

정책의 영향으로 승객의 불만도가 변화하며, 유지비가 발생할 수도 있습니다.
다시 게임플레이 화면으로 돌아가겠습니다. 창을 모두 닫아주세요.

일정시간이 지나면 이벤트가 발생합니다. 이벤트의 효과는 일정 기간 유지되며, 그 기간 동안 새로운 이벤트는 발생하지 않습니다.
이벤트는 무작위적으로 발생하며 승객 생성 속도의 변화, 역의 파괴, 승객 불만도의 증감 등 다양한 이벤트가 있습니다.

이벤트 창을 클릭하여 이벤트의 내용을 확인할 수 있습니다
이벤트 버튼을 클릭해보세요

승객이 원하는 목적지로 가지 못하면 불만도가 증가하여 게임오버가 될 수 있습니다. 또한, 잔고가 마이너스 상태에서 시간이 지나면 게임오버가 되므로 주의하세요.

좋습니다! 튜토리얼이 완료되었습니다. 지금부터 Poly-Metro를 즐겁게 플레이 하시기 바랍니다!

**Comment by seong0929** [comment]
초안 확정
