### ISSUE TITLE
Save 후 역 모양이 고정되어 나옴

### ISSUE THREAD

**Issue by cstrnull00** [Tiny-Metro/Tiny-Metro#127]
![image](https://user-images.githubusercontent.com/46642837/219600387-632547f3-373b-475d-bf9c-73998ffb7283.png)
Save 후 역을 다시 불러오는 과정에서 역 모양이 저장되지 않는 버그가 발견되었습니다.
![image](https://user-images.githubusercontent.com/46642837/219600705-6e1e4cd3-cff2-4f2f-a16c-62202aac96cf.png)

**Comment by yoon-H** [comment]
#138 
스폰액터 완료를 늦추는 방식으로 해결
