### ISSUE TITLE
Mesh 각도 조정 필요

### ISSUE THREAD

**Issue by cstrnull00** [Tiny-Metro/Tiny-Metro#128]
![image](https://user-images.githubusercontent.com/46642837/219601332-08436c5c-26b2-4f61-8f60-9aba8ad28aec.png)
![image](https://user-images.githubusercontent.com/46642837/219601350-10ae3fab-142a-4afb-b8fb-611055d0a45a.png)
![image](https://user-images.githubusercontent.com/46642837/219601369-cdf3d476-35dd-4ae1-9beb-6c226afad5bd.png)

현재 삼각형 역의 Mesh가 의도한 각도와 다르게 나옵니다. z축으로 30도 회전해야 합니다.

추가적으로 다른 역의 Mesh들도 확인해주시기 바랍니다.

**Comment by ruru14** [comment]
#129 
수정완료
