### ISSUE TITLE
카메라 움직임 제한 변경하는 법

### ISSUE THREAD

**Issue by AzureSoda** [Tiny-Metro/Tiny-Metro#131]
<h1> BP_RtsController 카메라 움직임 제한 변경하는 법 <h1>
XLeftLimit, XRightLimit, YUpLimit, YDownLimit 값을 변경하면 마우스로 이동할때나 키보드로 이동할때 둘다 값을 한번에 제한할 수 있습니다.
<h1> 1. 마우스로 카메라 움직일때 카메라 제한 변경하는 법 <h1>

MoveRtsCamera with Mouse 이 부분에서
![image](https://user-images.githubusercontent.com/49617190/219881126-ef0d2888-fab4-488e-bd9b-68510c18e4bb.png)
<hr>

![image](https://user-images.githubusercontent.com/49617190/219881208-a564be3d-85fc-458d-8b4e-48c34cea957f.png)
이 부분에서 변수 XLeftLimit을 바꾸면 카메라의 움직임의 왼쪽 제한을 바꿀 수 있습니다.
<hr>

![image](https://user-images.githubusercontent.com/49617190/219881258-1de2e1e0-9e24-40b7-864e-3d337bb3ddc8.png)
이 부분에서 변수 XRightLimit을 바꾸면 카메라의 움직임의 오른쪽 제한을 바꿀 수 있습니다.
<hr>

![image](https://user-images.githubusercontent.com/49617190/219881329-905bf6cf-9d3c-4f60-848d-702cb7a4dad7.png)
이 부분에서 변수 YUpLimit을 바꾸면 카메라의 움직임의 위쪽 제한을 바꿀 수 있습니다.
<hr>

![image](https://user-images.githubusercontent.com/49617190/219881291-5a295989-4bbb-4972-8ee1-0f9ebfe9ab00.png)
이 부분에서 변수 YDownLimit을 바꾸면 카메라의 움직임의 아래쪽 제한을 바꿀 수 있습니다.

<hr>

<h1>2. 키보드로 마우스 움직일 때 카메라 움직임 제한하는 법 <h1>

![image](https://user-images.githubusercontent.com/49617190/224527801-887ae0b8-36e0-43af-9615-529064f2b9c9.png)

이 부분에서 변수 YDownLimit을 바꾸면 카메라의 움직임의 아래쪽 제한을 바꿀 수 있습니다.

<hr>

![image](https://user-images.githubusercontent.com/49617190/224527892-329c138d-7458-4171-a55b-6f47363d197c.png)
이 부분에서 변수 YUpLimit을 바꾸면 카메라의 움직임의 위쪽 제한을 바꿀 수 있습니다.

<hr>

![image](https://user-images.githubusercontent.com/49617190/224527923-6cef25f5-6a94-4334-97b2-4870f6377c28.png)
이 부분에서 변수 XRightLimit을 바꾸면 카메라의 움직임의 오른쪽 제한을 바꿀 수 있습니다.
<hr>

![image](https://user-images.githubusercontent.com/49617190/224527956-8c55321f-02d9-42c1-916e-c2647820d4b6.png)
이 부분에서 변수 XLeftLimit을 바꾸면 카메라의 움직임의 왼쪽 제한을 바꿀 수 있습니다.

**Comment by cstrnull00** [comment]
W, A, S, D로 움직일 때는 카메라 이동에 LOCK이 걸리지 않는데 이 부분 개발 가능할까요?

**Comment by seong0929** [comment]
이 작업 c++로 변환하여 완료되었으면, close해주세요.
