### ISSUE TITLE
Lane 연장/선택 해제 방식 변경에 대한 의견

### ISSUE THREAD

**Issue by cstrnull00** [Tiny-Metro/Tiny-Metro#133]
현재 버전에서 Lane을 연장하고자 할 때마다 Lane의 handle을 클릭했다가 새로 클릭하는 게 번거롭습니다. 

1. Lane의 handle을 한 번 클릭하고 역을 클릭할 때마다 Lane이 연장
2. Lane 선택을 해제하려면 허공을 클릭하거나 역을 제외한 오브젝트(열차, UI 등)를 클릭했을 때 선택 해제

이런 쪽이 사용자 입장에서 비교적 편리할 것 같습니다.

**Comment by yoon-H** [comment]
48a64d7
