### ISSUE TITLE
줌아웃 후 열차 drag 시 배치 불가 버그

### ISSUE THREAD

**Issue by cstrnull00** [Tiny-Metro/Tiny-Metro#137]
![image](https://user-images.githubusercontent.com/46642837/219931170-03c80c4f-c05e-4afe-b8db-2f4f0106394e.png)
초기 화면에서는 drag 시 배치 가능하지만 줌아웃 한 후 drag 하면 사진과 같이 화면 정가운데에 위치하고 조작이 되지 않습니다. 이후 마우스 버튼을 놓으면 그 자리에 남지 않고 사라집니다.

**Comment by ruru14** [comment]
열차 배치 알고리즘을 수정함으로 해결
