### ISSUE TITLE
Grid 꼭짓점마다 열차가 멈추는 현상

### ISSUE THREAD

**Issue by cstrnull00** [Tiny-Metro/Tiny-Metro#150]
현재 열차가 역에서만 멈추는 것이 아니라 Grid 꼭짓점마다 멈추는 현상이 있습니다.
확인 부탁드립니다.

**Comment by ruru14** [comment]
Train의 이동을 역 - 꼭짓점 - 역 에서 역 - 역으로 변경하여 완화
