### ISSUE TITLE
승객 겹침 버그

### ISSUE THREAD

**Issue by cstrnull00** [Tiny-Metro/Tiny-Metro#151]
![image](https://user-images.githubusercontent.com/46642837/221392974-b71e4d90-fecb-4c1b-bfd4-2cd2d86d71fc.png)
현재 역에 대기할 수 있는 승객 수를 초과하여 승객이 겹쳐서 생기는 이슈가 있습니다.

**Comment by ruru14** [comment]
시각적으로 보이는 승객의 갯수를 제한하는 것으로 해결 완료
