### ISSUE TITLE
인접리스트 보완

### ISSUE THREAD

**Issue by ruru14** [Tiny-Metro/Tiny-Metro#154]
- 현재의 문제점
  - AdjList[][]연산이 불가함 (가독성, 접근성이 떨어짐)
  - 리스트 접근 시, AdjItem을 인자로 사용할 수 없음

- 개선 방안
  - TMap의 경우, 배열연산자 (operator[])에 Key값을 사용할 수 있음
  - 구체적으로 다음과 같은 코드가 성립 (AdjItem은 Id, Type을 가진 구조체라 가정)
  ```
  TMap<AdjItem, TMap<AdjItem, float>> AdjList;
  AdjItem a(0, StationType::Triangle);
  AdjItem b(2, StationType::Star);
  AdjList[a][b];
  ```
  - 이 경우 문제점은, 2차원 Map으로 선언한 AdjList에 값을 삽입하는 것이 난해하다는 것
  - 따라서 Map을 감싸는 클래스를 만들고, 거기에 operator[] (AdjItem)을 오버로딩 하여 접근성을 강화
  ![KakaoTalk_20230226_204734366](https://user-images.githubusercontent.com/22653737/221488402-1e6a19e7-05a5-4966-b30c-7fc80e7faad8.png)
  - 위 코드는 예시

- 구체적인 결과 명세
  - StationInfo 구조체를 생성, 해당 구조체는 다음의 값을 가짐
    - int32 StationId
    - StationType Type
    - 위 구조체로 기존 Station의 Id와 Type을 교체
  - 다음의 코드가 성립할 수 있도록 해야 함
  ```
  AdjList[StationInfo][StationInfo]
  AdjList::Update(StationInfo, StationInfo, float)
  ```
  - Update함수는 삽입, 수정, 삭제 모두에 대응이 가능하지만, 경우에 따라 기능을 분리
 
- 참고 할 만한 자료
  - [TMap](https://docs.unrealengine.com/4.27/ko/ProgrammingAndScripting/ProgrammingWithCPP/UnrealArchitecture/TMap/)

**Comment by yoon-H** [comment]
#160

**Comment by ruru14** [comment]
인접리스트 구현 완료
