### ISSUE TITLE
Train이 다른 Lane을 따라가는 오류

### ISSUE THREAD

**Issue by cstrnull00** [Tiny-Metro/Tiny-Metro#158]
![제목 없는 동영상 - Clipchamp로 제작](https://user-images.githubusercontent.com/46642837/222876624-50a2bedc-f946-4fe7-aa91-c3de6c3370e7.gif)

2호선에 배치되어 역에 정지했던 Train이 겹쳐 있는 다른 Lane을 침범하는 버그가 발견되었습니다.
항상 이러는 것은 아닌 것 같은데 확인 부탁드립니다.

**Comment by ruru14** [comment]
해결완료
