### ISSUE TITLE
노선 UI 제작

### ISSUE THREAD

**Issue by cstrnull00** [Tiny-Metro/Tiny-Metro#164]
현재 버전에서는 Lane 끝의 T자 핸들을 이용하여 노선을 연장하거나 축소, 삭제할 수 있습니다. 하지만 현재 선택된 노선이 무슨 노선인지 알 수 없습니다. 

문서에 서술된 대로 우측 하단에 현재 선택할 수 있는/선택된 노선을 볼 수 있는 UI를 추가해야 합니다.

**Comment by seong0929** [comment]
- [x] 현재 버전에서는 Lane 끝의 T자 핸들을 이용하여 노선을 연장하거나 축소, 삭제할 수 있습니다. 하지만 현재 선택된 노선이 무슨 노선인지 알 수 없습니다.

- [ ] 문서에 서술된 대로 우측 하단에 현재 선택할 수 있는/선택된 노선을 볼 수 있는 UI를 추가해야 합니다.

**Comment by yoon-H** [comment]
[179a64e](https://github.com/Tiny-Metro/Tiny-Metro/commit/179a64ed5c8b9e2918ee6d3bcb0dcec84f91d610)
