### ISSUE TITLE
Lane 생성/삭제 시 Train 취급

### ISSUE THREAD

**Issue by cstrnull00** [Tiny-Metro/Tiny-Metro#167]
Lane 생성 시 Train이 하나 자동으로 생성되었으면 좋겠습니다. Train은 Lane이 생성되기 시작한 첫 역에 스폰합니다.

현재 버전에서는 Train이 있는 Lane을 삭제 시 강제 종료됩니다. 
Lane이 삭제될 경우 Train을 회수 처리하는 것으로 해주시면 되겠습니다.

**Comment by yoon-H** [comment]
[3e25a54](https://github.com/Tiny-Metro/Tiny-Metro/commit/3e25a542eb1baa38e774921b07c28fa7a6a23700)
[df9e230](https://github.com/Tiny-Metro/Tiny-Metro/commit/df9e2308b39647a02e9bbcf2b7146404daba1dce)
