### ISSUE TITLE
노선 모양 변경 기능

### ISSUE THREAD

**Issue by cstrnull00** [Tiny-Metro/Tiny-Metro#169]
현재 노선이 한번 생성되면 그 모양은 변경되지 않습니다. 

노선이 생성될 때 연장하려면 한 가지 방향으로 밖에 되지 않는데 이런 경우 다리나 터널의 사용에 있어 불합리한 모양으로 생성될 가능성이 높습니다.

노선을 더블 클릭하면 꺾이는 지점이 반대 지점으로 변경되는 기능의 추가가 필요합니다.

**Comment by yoon-H** [comment]
[c3ca603](https://github.com/Tiny-Metro/Tiny-Metro/commit/c3ca6030c0627f6e3ea346ed8128b6f8e6c3b062)
