### ISSUE TITLE
팝업 토글화 논의

### ISSUE THREAD

**Issue by cstrnull00** [Tiny-Metro/Tiny-Metro#203]
현재 팝업 창(상점, 정책, 은행 등)을 띄우고 싶을 때 해당 아이콘을 클릭한 후, UI 우측 상단의 x표를 클릭해야 창이 닫아집니다. 다시 그 아이콘을 클릭하면 닫아지는 기능을 추가하는 것도 좋을 것 같습니다.

**Comment by KimDa99** [comment]
해결됨
