### ISSUE TITLE
플러그인 LuaMachine 빌드 오류 

### ISSUE THREAD

**Issue by KimDa99** [Tiny-Metro/Tiny-Metro#215]
LuaMachine이 제대로 빌드가 되지 않는 이슈가 있었습니다.

문제 원인은 \Plugins\LuaMachine\Source\ThirdParty\x64\liblua53_win64.lib 파일이 없는 것이었습니다.

.gitignore파일의 

```
# Compiled Static libraries
*.lai
*.la
*.a
*.lib

```
부분에 걸려 깃에 업로드가 안 된 것으로 예상됩니다.

**Comment by KimDa99** [comment]
[x64.zip](https://github.com/Tiny-Metro/Tiny-Metro/files/11711760/x64.zip)
해당파일입니다

**Comment by ruru14** [comment]
파일 푸시 후 클로즈 바랍니다.

**Comment by KimDa99** [comment]
https://github.com/Tiny-Metro/Tiny-Metro/pull/218
