### ISSUE TITLE
시야 바깥 역 후보지 생성 시 알림

### ISSUE THREAD

**Issue by seong0929** [Tiny-Metro/Tiny-Metro#231]
현재 시야 바깥에 역이 생성될 때 알아차리기가 어렵습니다.

생각하고 있는 바는 

1. 이벤트 알림 창에 역 후보지 생성 메시지 
2. 화면 바깥 방향에 펄스 이펙트
3. 새로 생긴 역 주변으로 몇 초간 펄스 이펙트

이렇게 생각하고 있습니다.

**Comment by seong0929** [comment]
역 생성 시
1. 역 주변으로 검정색 펄스가 생김
2. 시야 밖에 있을 때, 해당 방향 카메라 모서리에 검정색으로 점멸

추가 구현
- 역 생성 시 뉴스 알림으로 역 생성을 알린다. "새로운 역이 생성되었습니다."라는 알림과 클릭 시 뉴스 알림 창이 나오고 해당 문구에 돋보기 버튼 클릭 시 해당 역으로 이동

**Comment by ruru14** [comment]
1. 검정색 펄스 및 모서리의 점멸 이펙트에 대한 구체적인 시안이 필요합니다.
2. 뉴스 알림의 UI가 필요합니다.

**Comment by seong0929** [comment]
1. 역이 시야 밖으로 상단에 생길 경우
- ![image](https://github.com/Tiny-Metro/Tiny-Metro/assets/50050003/f25a90cc-fe61-42ce-8d54-9aa90fbabb36)
- ![image](https://github.com/Tiny-Metro/Tiny-Metro/assets/50050003/0f9397ff-583d-4be8-8e9d-cbcc813c3c63)
2. 역이 시야 밖으로 우측 하단에 생길 경우
- ![image](https://github.com/Tiny-Metro/Tiny-Metro/assets/50050003/a90ad2d3-806c-4f97-b89a-2177259f7af7)
- ![image](https://github.com/Tiny-Metro/Tiny-Metro/assets/50050003/0f9397ff-583d-4be8-8e9d-cbcc813c3c63)

카메라 모서리에 1초간 점멸

**Comment by seong0929** [comment]
검정색 펄스 예시
![KakaoTalk_20230628_103827289](https://github.com/Tiny-Metro/Tiny-Metro/assets/50050003/845a53a6-3c98-472a-9433-07039bd726d6)

**Comment by seong0929** [comment]
현재 뉴스칸을 예시로 보여주겠습니다.
- ![image](https://github.com/Tiny-Metro/Tiny-Metro/assets/50050003/53528a21-db8a-4814-8c84-946d3f2efb0a)
- 새로운 역이 생길 시 뉴스에 "새로운 역이 생성되었습니다." 문구와 돋보기 아이콘이 등장합니다.
- 돋보기 아이콘 클릭 시 해당 역을 카메라 이동합니다.(줌인 줌아웃 없이, 해당 역이 중심이 되도록 이동 )
- 클릭을 했던 역 생성 알림은 돋보기 아이콘이 사라집니다.
- 만약 확인을 하지 않았다면, 돋보기 아이콘은 그대로 남습니다.

p.s. 뉴스 알림의 경우, 아직 기획팀에서 필요 여부를 판단하고 있습니다.(23.06.28)

**Comment by ruru14** [comment]
모서리에 생기는 검은색 음영과 역에 발생하는 펄스는 지속시간이 어느정도 되어야 하나요?
