### ISSUE TITLE
통계 보완 작업 (유저 행동 집계)

### ISSUE THREAD

**Issue by cstrnull00** [Tiny-Metro/Tiny-Metro#238]
통계 항목에서 유저의 행동에 대한 계수를 확인할 수 있어야 합니다.
확인 가능한 행동의 예시는 다음과 같습니다
- 순환선을 N개 만들었습니다.
- 노선을 N회 연장했습니다.
- 열차를 N회 배치했습니다.
- 열차를 N회 구매했습니다.

장르가 시뮬레이션 게임인 만큼, 확인 가능한 정보의 풀이 넓어야 한다고 생각합니다.
가능한 한 모든 행동에 대한 집계가 가능하도록 정리 바랍니다.

**Comment by cstrnull00** [comment]
제공할 수 있는 통계의 종류는 다음과 같습니다.

* 노선
  * 총합 
    * 총 건설된 노선의 수 (최대 8개)
    * 현재 배치된 순환선의 개수
    * 노선 삭제 횟수
  * 개별
    * 노선 이용객 수 (탑승 기준 / 열차 삭제로 인한 하차 후 재탑승은 카운트 X)
    * 주간/누적 노선 수지 (승차 요금 - 운영비)
    * 순환선 여부
    * 이용 중인 다리와 터널의 개수
    * 환승역 수 (두 개 이상의 노선이 지나는 역)
    * 운영 중인 역의 개수
    * 노선의 축소/연장 횟수
    * 노선 모든 역의 평균 불만도
    * 운행 중인 열차/객차의 수
* 역
  * 현재 역을 지나는 노선의 수
  * 주간/누적 이용 승객 합
  * 주간/누적 운영 수지 (승차 요금 - 운영비)
  * 불만도
  * 승객의 평균 대기 시간
* 열차
  * 딸린 객차의 수
  * 주간/누적 승객 탑승 수 (딸린 객차를 포함)
  * 옮겨진 횟수
  * 업그레이드
* 상점
  * 총 상점 이용 금액
  * 아이템별 구매 횟수
  * 총 구매 횟수
* 대출 
  * 대출 이용 횟수
  * 총 대출 금액
  * 총 상환 금액
  * 잔여 대출금
  * 납부한 총 이자

**Comment by ruru14** [comment]
- 해당 통계값을 UI에 적절히 노출시키는 방법에 대한 아이디어가 필요합니다
  - 카테고리 형식 구분에 대한 아이디어가 있었습니다. (버튼, 책갈피 등)
- 역과 열차 관련해서, 초안의 값들은 개별 객체에 관한 값입니다. 통계 화면에 노출될 값에 대한 정리가 필요합니다.
- 이하는 회의를 통해 결정된 사안입니다.
  - 개별 ID를 가지는 객체 (역, 열차)에 대한 API는 제공하지 않습니다.
  - 개별 객체에 관한 값은 해당 객체의 정보 UI에 노출될 값 입니다.

**Comment by cstrnull00** [comment]
위에 제시된 통계 항목들이 보여질 페이지는 각각 아래와 같습니다.

* 메인 화면 우측 상단
![image](https://github.com/Tiny-Metro/Tiny-Metro/assets/46642837/6b0de6a5-d97c-4202-8f6d-911aa8be0f69)
  * 보유 금액
  * 목적지에 도착한 승객 수
* 역 정보 UI
  * 주간/누적 이용 승객 합
  * 주간/누적 운영 수지 (승차 요금 - 운영비)
  * 승객의 평균 대기 시간
  * 현재 불만도 (역 정보 UI에서는 수치 표기)
* 열차 정보 UI
  * 주간/누적 승객 탑승 수 (딸린 객차 포함)
* 은행
  * 잔여 대출금
* 설정 - 통계 페이지
  * 위에 언급되지 않은 다른 모든 항목
 
통계 페이지에 대한 UI 디자인은 이어서 추가하도록 하겠습니다.

**Comment by cstrnull00** [comment]
통계 페이지에 대한 UI 디자인은 플래닛 주의 UI를 참고하였습니다.
아래 예시 사진 첨부하겠습니다.
![통계UI 제안](https://github.com/Tiny-Metro/Tiny-Metro/assets/46642837/d8f3b70a-b875-4ac4-8181-fc1e41868c80)

**Comment by cstrnull00** [comment]
[통계 UI.pptx](https://github.com/Tiny-Metro/Tiny-Metro/files/11990090/UI.pptx)

**Comment by seong0929** [comment]
@KimDa99 통계 관련 UI는 위 ppt와 같습니다.
해당 통계 UI 항목에 들어갈 내용들은 다음과 같습니다.
1. 개요
  - 누적 승객 수
  - 주간 승객 수
  - 누적 수익
  - 주간 수익
  - 누적 지출
  - 주간 지출
  - 평균 불만도
  - 운영 중인 역의 갯수
- ![image](https://github.com/Tiny-Metro/Tiny-Metro/assets/50050003/fe6769ee-69ad-49df-a788-70b1f41db491)

2. 노선
 - 총 건설된 노선의 수
 - 노선 수정/삭제 횟수**(단, 연장은 포함되지 않습니다.)**
 - 노선 색깔 별(호선 별) 데이터
   - 누적 노선 이용객 수
   - 주간 노선 수지
   - 누적 노선 수지
   - 이용 중인 다리와 터널의 수
   - 환승역 수
   -  운영 중 역의 수
   - 해당 노선의 수정/축소 횟수
   - 노선 모든 역의 평균 불만도
   - 운영 중인 열차/객차 수
   - 순환선 여부
- ![image](https://github.com/Tiny-Metro/Tiny-Metro/assets/50050003/74768a99-3b07-4670-97cf-75c24f81a46d)
_**노선 색깔 별 데이터 중 "노선의 축소/연장 횟수"는 오타로 "해당 노선의 수정/축소 횟수"가 맞습니다.**_

3. 상점
- 총 상점 이용 금액
- 총 구매 횟수
- 열차
  - 구매 횟수
  - 배치된 횟수
  - 옮겨진 횟수
  - 회수된 횟수
  - 업그레이드 횟수
- 객차
  - 구매 횟수
  - 배치된 횟수
  - 옮겨진 횟수
  - 회수된 횟수
  - 업그레이드 횟수
- 다리
  - 구매 횟수
  - 배치된 횟수
- 터널
  - 구매 횟수
  - 배치된 횟수
- ![image](https://github.com/Tiny-Metro/Tiny-Metro/assets/50050003/a5d359a2-873f-49c7-a865-b430d9feac65)

4. 은행
- 대출 상품 이용 횟수
- 총 상환 금액
- 총 대출 금액
- 납부한 총 이자
- ![image](https://github.com/Tiny-Metro/Tiny-Metro/assets/50050003/25363cd0-be3b-474d-9b41-d244e122bf36)

**Comment by seong0929** [comment]
원래 있던 이미지를 제외한 통계에 사용할 아이콘 정리입니다.
- [노션](https://www.notion.so/df519ed465a446a0b4011ad5cbe5cce4)
