### ISSUE TITLE
새로운 역이 생성되었음을 알려주는 펄스가 초기 3역에서 펄스가 끊기지 않음

### ISSUE THREAD

**Issue by AzureSoda** [Tiny-Metro/Tiny-Metro#326]
![image](https://github.com/Tiny-Metro/Tiny-Metro/assets/49617190/a77d6e6c-0764-4ff2-b34b-72c4563b304c)

새로운 역이 생성되었음을 알려주는 펄스가 초기 3역에서 펄스가 끊기지 않음

**Comment by ruru14** [comment]
https://github.com/Tiny-Metro/Tiny-Metro/pull/358
해결
