### ISSUE TITLE
버그-투자 미션 수락 후(Mon), 미션을 수행하지 않았는 데 3일 후(Thu) 코딩되지 않은 돈(5000)이 들어옴.

### ISSUE THREAD

**Issue by AzureSoda** [Tiny-Metro/Tiny-Metro#327]
투자 미션 수락 후(Mon), 미션을 수행하지 않았는 데 3일 후(Thu) 코딩되지 않은 돈(5000)이 들어옴.

- 현재까지 확인된 투자 미션 1003, 1004, 1005, 1007 ('어떤 역도 불만도 50을 넘지 않도록 하세요.', '을 업그레이드하세요.')

- 다른 돈이 들어간 보상의 합은 6200 (투자 미션 1001, 1002, 1003, 1004, 1007, 1008, 1009, 1010, 1011)(300, 500, 800, 300, (300, 500), 500, 800, 2000, 500, 500)
![image](https://github.com/Tiny-Metro/Tiny-Metro/assets/49617190/cd4204b5-fe25-4fcb-b3ef-586abf590921)
![image](https://github.com/Tiny-Metro/Tiny-Metro/assets/49617190/06c44116-7d91-4e85-84e1-5f9b2707c6ea)

- 앞선 상황 이후 2주차에 진입하여(Mon) 두 미션 수락한 뒤 3일 뒤(Thu)에 미션이 완료됨

- 화요일(Tue)에 미션 수락 시 금요일(Fri)에 미션이 완료됨
![image](https://github.com/Tiny-Metro/Tiny-Metro/assets/49617190/e37f211a-765a-486e-8899-9da85aed04fa)

**Comment by seong0929** [comment]
DataStruct 개선 이후로 발생하지 않는 버그 입니다.
