### ISSUE TITLE
버그-완료한 미션이 몇일이 지나도 남아 있음

### ISSUE THREAD

**Issue by AzureSoda** [Tiny-Metro/Tiny-Metro#328]
완료한 미션이 몇일이 지나도 남아 있음
- 다음주가 되면 사라짐
    
![image](https://github.com/Tiny-Metro/Tiny-Metro/assets/49617190/ac9e615e-568e-4788-a1a5-04ac6e3c9a74)

**Comment by ruru14** [comment]
https://github.com/Tiny-Metro/Tiny-Metro/discussions/197
논의 참조 바랍니다.
완료된 미션은 다음주에 교체되는것으로 구현했습니다.
