### ISSUE TITLE
버그-대출을 하지 않았는 데, Investment.1009가 등장

### ISSUE THREAD

**Issue by AzureSoda** [Tiny-Metro/Tiny-Metro#329]
대출을 하지 않았는 데, Investment.1009가 등장

<pre>
<code>
function Appearance()
    totalloanmoney = loan.TotalUsingLoanCount
    return totalloanmoney ~= 0
end
</code>
</pre>

**Comment by ruru14** [comment]
투자미션은 전수조사 다시 해주세요
