### ISSUE TITLE
버그-게임을 종료하는 방법이 필요

### ISSUE THREAD

**Issue by AzureSoda** [Tiny-Metro/Tiny-Metro#334]
게임을 종료하는 방법이 필요함

- 메인화면에서 뒤로 가기를 눌렀을 때 "게임을 종료하시겠습니까?" 라고 나오는 팝업창이 필요

**Comment by ruru14** [comment]
https://github.com/Tiny-Metro/Tiny-Metro/pull/348
추가했습니다.
