### ISSUE TITLE
lua Investment.1003 nil 오류

### ISSUE THREAD

**Issue by seong0929** [Tiny-Metro/Tiny-Metro#351]
- 기존에 있던 content>script>investment>savedseoul 파일도 삭제하면서 검토해보았습니다.

![image](https://github.com/Tiny-Metro/Tiny-Metro/assets/50050003/53c0e7eb-e0d5-4ccb-93d1-29c950322f5e)

_LogLuaMachine:_ Error: Lua error: attempt to call a nil value_
_LogLuaMachine: Error: Lua error: ...Content/Script/Investment/SavedSeoul/Investment.1003.lua:29: attempt to index a nil value (field '?')_
_LogLuaMachine: Error: Lua error: attempt to call a nil value_

- 아래 코드에 한국어 주석 있는 부분에서 오류가 났습니다.
- stations 이 없는 경우도 예외 처리도 추가해 놓은 상태입니다.
- 현재 develop-InvestLua를 통해 확인할 수 있습니다.

<pre>
<code>
-- Complaint management
local additional_needs_1003 = 50
local reward_money_1003 = 800

-- Investment condition
function InvestmentData()
    local Data = {}
    Data.message = '어떤 역도 불만도 ' .. additional_needs_1003 .. '을 넘지 않도록 하세요.'
    Data.time_require = 7
    Data.award = reward_money_1003 .. "$"

    return Data
end

-- Call when investment start
-- Used save info when start
function Start()
end

-- Investment appear condition
function Appearance()
    local stations = GetStationInfos()

    if stations == nil then
        return false
    end

    for i=0, #stations do
        -- 아래 조건부에서 오류가 발생했습니다.
        if stations[i].Complain > additional_needs_1003 then
            return false
        end
    end
    return true
end

-- Investment success condition
function Process()
    local start_time = GetTimestampAtStart(1003)
    local cur_time = GetTimestamp()
    local stations = GetStationInfos()

    local all_stations_limit = true

    for i = 0, #stations do
        if stations[i].Complain > additional_needs_1003 then
            -- If the deadline is exceeded, it immediately fails.
            all_stations_limit = false
            break
        end
    end

    if all_stations_limit then
        if (start_time.Date - cur_time.Date) <= InvestmentData().time_require then
            return continue
        else
            return success
        end
    else
        return fail
    end
end

-- Investment award
function Award()
    AddMoney(reward_money_1003)
end

InvestmentDataStruct= {}
InvestmentDataStruct.InvestmentData = InvestmentData
InvestmentDataStruct.Start = Start
InvestmentDataStruct.Appearance = Appearance
InvestmentDataStruct.Process = Process
InvestmentDataStruct.Award = Award

return InvestmentDataStruct
</code>
</pre>

**Comment by ruru14** [comment]
API가 아니라 코드문제같습니다.
이하 코드 정상 작동합니다.
```
stations = GetStationInfos()
for i, v in pairs(stations) do
    print(v.Complain) 
end
```

**Comment by ruru14** [comment]
추가로, Lua코드에 대한 간단한 테스트 기능을 만들어놨었는데, 해당 기능 공유합니다.
![image](https://github.com/Tiny-Metro/Tiny-Metro/assets/22653737/ee4018e1-221d-4302-b774-3dbb68eb9065)
콘솔 UI의 Call TestFunction버튼을 클릭할 시, 아래 경로의 TestFunction함수가 호출됩니다.<br>
**Content/Script/TestScript.lua**<br>
테스트 시 이용 바랍니다.
