### ISSUE TITLE
하단의 UI에서 노선 색 표시한 아이콘이 커지지 않음

### ISSUE THREAD

**Issue by AzureSoda** [Tiny-Metro/Tiny-Metro#355]
하단의 UI에서 노선 색 표시한 아이콘이 커지지 않음

**Comment by ruru14** [comment]
![image](https://github.com/Tiny-Metro/Tiny-Metro/assets/22653737/6f861e40-bb80-44fe-b449-afe5d851acca)
정상 작동합니다.
