### ISSUE TITLE
로드 후, 노선 번호 판정

### ISSUE THREAD

**Issue by ruru14** [Tiny-Metro/Tiny-Metro#361]
![image](https://github.com/Tiny-Metro/Tiny-Metro/assets/22653737/4ae1d799-1992-49eb-bae3-05c03350af8b)
발생 조건은 다음과 같습니다.
1. 최초 게임 시작 이후 노선 생성
2. 게임 종료 (저장)
3. 게임 재시작 (로드)
4. 기존 노선에 운행중인 열차 드래그
5. 기존 노선에 드롭
6. 열차 색이 노선과 맞지 않습니다.

**Comment by yoon-H** [comment]
[94b257e](https://github.com/Tiny-Metro/Tiny-Metro/commit/94b257ef8ffb2cbe8f8a31fa3dd88d879421ada6)
