### ISSUE TITLE
여러 역을 지나는 한 레인 변경

### ISSUE THREAD

**Issue by seong0929** [Tiny-Metro/Tiny-Metro#363]
- 노선 모양 변경할 때 한 노선의 여러 역을 동시에 변경이 가능한가요? 
- 레인 변경 취소가 가능한가요?
   -  레인 변경 후 다시 원래 자리로 이동시키는 기능이 필요한가요?

**Comment by seong0929** [comment]
- 역과 역 사이의 노선 클릭 시 해당 노선은 변경이 가능합니다.
- 변경 후 다시 변경 시 원래 자리로 돌아갑니다.
- 두 역 사이의 노선만 변경이 됩니다.

**Comment by yoon-H** [comment]
[c3ca603](https://github.com/Tiny-Metro/Tiny-Metro/commit/c3ca6030c0627f6e3ea346ed8128b6f8e6c3b062)
