### ISSUE TITLE
UserHUD 복수 생성

### ISSUE THREAD

**Issue by ruru14** [Tiny-Metro/Tiny-Metro#367]
![image](https://github.com/Tiny-Metro/Tiny-Metro/assets/22653737/22c13552-9651-4038-8121-b2ce1f541841)
발생 브랜치 : develop
UserHUD가 복수 생성이 시도됩니다.
해당 이슈로 다음 문제가 발생합니다.
- Station Tutorial의 진행이 불가합니다.

**Comment by KimDa99** [comment]
https://github.com/Tiny-Metro/Tiny-Metro/pull/373
