### ISSUE TITLE
Destroyed station의 Load시 Material이 정상적이지 않은 현상

### ISSUE THREAD

**Issue by ruru14** [Tiny-Metro/Tiny-Metro#368]
![image](https://github.com/Tiny-Metro/Tiny-Metro/assets/22653737/534fc237-9716-44ca-9729-4831186076d4)
파괴된 역이 로드될 시 일반 Material로 나타나는 현상이 발생합니다.

**Comment by yoon-H** [comment]
[94b257e](https://github.com/Tiny-Metro/Tiny-Metro/commit/94b257ef8ffb2cbe8f8a31fa3dd88d879421ada6)
