### ISSUE TITLE
Destroyed station을 이용한 노선 생성이 가능한 현상

### ISSUE THREAD

**Issue by ruru14** [Tiny-Metro/Tiny-Metro#369]
![image](https://github.com/Tiny-Metro/Tiny-Metro/assets/22653737/4c682277-f54d-4ca0-8b91-dcd68730f549)
파괴된 역을 이용한 노선 생성이 가능한 현상이 발생합니다.

**Comment by seong0929** [comment]
- 파괴된 역은 생성되지 않습니다.
- 노선이 연결된 상태에서 역이 파괴될 시 노선이 삭제되지 않고, 해당 역이 비활성화 됩니다.
  - 파괴된 역의 비활성화 역을 풀려면 돈을 내면(재건하면) 됩니다.
  - 열차는 파괴된 역에서 정차하지 않고 지나갑니다.

**Comment by yoon-H** [comment]
[9fa952b](https://github.com/Tiny-Metro/Tiny-Metro/commit/9fa952bd3de2eb941876d753ae28f05df366f012)
