### ISSUE TITLE
열차 속도 조절하는 방법이 필요합니다.

### ISSUE THREAD

**Issue by seong0929** [Tiny-Metro/Tiny-Metro#398]
열차 속도가 승객 생성에 따라가지 못 해 2주밖에 플레이 하지 못 하는 문제가 있습니다. 이를 해결하기 위해 열차 속도를 올리는 방법이 필요합니다.
승객 생성 속도를 기준으로 상점 물품이나 역 생성의 수치를 조정 했었으니, 열차 속도만 조절하면 될 거 같습니다.

**Comment by mille-feu** [comment]
BP_Train의 아웃라이너에 이하 항목이 있습니다.
![image](https://github.com/Tiny-Metro/Poly-Metro/assets/22653737/4acf2858-790d-404d-b47f-313f8799d049)

MaxWalkSpeed를 조정하면 열차의 이동 속도가 변동됩니다.<br>
현재 업그레이드 전 300, 업그레이드 후 400으로 되어있습니다.

**Comment by seong0929** [comment]
[document 인게임 wiki](https://github.com/Tiny-Metro/Poly-Metro/wiki/Document:-%EC%9D%B8%EA%B2%8C%EC%9E%84#%EC%97%B4%EC%B0%A8)에 업데이트도 하였습니다.
업그레이드 전 400, 업그레이드 후 600으로 조정하시면 됩니다.

이전 플레이에는 2주 이전에 불만도가 꽉 차 게임 오버가 되었으나, 현재는 돈이 부족해 게임 오버가 됩니다. 해당 [버그](https://github.com/Tiny-Metro/Poly-Metro/issues/353)로 인해 돈과 관련한 벨런스를 못 했지만, 많은 승객이 타고 내리는 것을 손수 계산해보았습니다.

즉, 빠른 시일 내에 게임 오버가 되는 것을 방지하였습니다.

**Comment by mille-feu** [comment]
열차 속도 반영되었습니다.
