### ISSUE TITLE
열차 업그레이드 UI가 지속적으로 등장하는 현상

### ISSUE THREAD

**Issue by cstrnull00** [Tiny-Metro/Tiny-Metro#403]
운행 중인 열차를 짧게 탭하면 열차 업그레이드 UI가 등장하는 것까지는 잘 작동하지만
열차 업그레이드 UI를 닫은 후에 무작위 지역을 탭했을 때 방금 전에 열었던 열차 업그레이드 UI가 지속적으로 등장하는 현상이 발생합니다.
확인 후 조치 부탁드립니다.

**Comment by mille-feu** [comment]
39bc20d
해결
