### ISSUE TITLE
Train direction 설정 오류

### ISSUE THREAD

**Issue by mille-feu** [Tiny-Metro/Tiny-Metro#406]
발생 브랜치 : develop
![image](https://github.com/Tiny-Metro/Poly-Metro/assets/22653737/6d5ccd64-687a-4048-b439-aed9487495be)
- 노선 연결은 네모(12시) -> 세모(9시) -> 동그라미(5시) 순서로 연결했습니다.
- 열차가 네모에서 동그라미까지 주행 이후, 동그라미와 세모 원을 반복해서 순회합니다
- TrianDirection 관련 오류로 추측됩니다.
- 역 도착 시 TrainDirection을 수정하는 코드는 다음과 같습니다.
![image](https://github.com/Tiny-Metro/Poly-Metro/assets/22653737/dfe22335-1268-4a0c-945d-1c5d68bef76d)

**Comment by yoon-H** [comment]
SetDirectionInit의 두 번째 매개변수가 노선의 각 지점(LaneArray의 World Coordination)과 정확히 동일해야 열차 방향을 알 수 있습니다.
GetActorLocation으로 값을 받기보다는 현재 도달한 역의 FIntPoint 값을 받아오면 탐색이 가능할 것 같네요.

**Comment by mille-feu** [comment]
해결됐습니다.
