### ISSUE TITLE
Brainstorming : Time class

### ISSUE THREAD

**Issue by ruru14** [Tiny-Metro/Tiny-Metro#64]
- Time 클래스 제작 필요
  - 기반 클래스는 액터로
  - GameMode에서 스폰하는 형식 등으로, 사용하는 데에 추가적인 조작이 필요 없도록 제작
  - Time클래스의 주요 기능은 게임의 경과시간 (Save, Load 포함)을 알 수 있도록  하는 것
  - Time클래스의 [ElapseTime]변수가 게임의 경과 시간을 저장
  - Time클래스의 TickEvent의 DeltaTime만큼 ElapseTime을 증가시킴
  - ElapseTime을 저장하는 것으로, 게임의 경과 시간을 저장할 수 있음
  - 사용은 GameMode클래스의 GetTime과 같은 함수로 구현하여, Time클래스에 직접적으로 접근할 필요가 없도록 제작

**Comment by yoon-H** [comment]
- AGameModeBaseSeoul을 변수에 캐스팅합니다.
  ![image](https://user-images.githubusercontent.com/71068767/210393051-760a67c6-198b-4f31-9fac-d676c2ab68da.png)
  ![image](https://user-images.githubusercontent.com/71068767/210392955-887e75ee-c0f1-4abb-86a4-6fa989285d70.png)

- GetTime() 함수를 사용해서 경과 시간을 float로 받을 수 있습니다.
  ![image](https://user-images.githubusercontent.com/71068767/210393443-fafaabbf-bd99-4fad-9ec9-02e846429182.png)

- GameModeBaseSeoul에만 적용한 상태입니다.

**Comment by ruru14** [comment]
@yoon-H 
게임 플레이 시간에 대한 값이기 때문에, GameMode보다는 PlayerState가 어울릴 것 같습니다.
번거롭겠지만, GameMode에 구현된 해당 내용을 PlayerState로 이동시켜주시기 바랍니다.

- 프로젝트의 PlayerState클래스는 TinyMetroPlayerState(.cpp / .h)입니다.
- PlayerState의 접근 방법은 아래와 같습니다.
```
ATinyMetroPlayerState* PlayerState = 
    GetWorld()->GetPlayerControllerIterator()->Get()->GetPlayerState<ATinyMetroPlayerState>();
```

추가적으로, 함수 서명을 다음과 같이 수정, 추가해주시기 바랍니다.
- GetTime함수는 GetPlayTimeSec로 이름을 수정해주시기 바랍니다.
- 게임 기준, 현재가 몇 번째 날인지 나타내는 int32 GetDay()함수를 추가해주시기 바랍니다.
  - 하루가 몇 초인지에 대한 정보는 GameMode의 GetDayTime()함수에 저장되어 있습니다.
- 게임 기준, 현재가 몇 시인지 나타내는 float GetDayTime()함수를 추가해주시기 바랍니다.
  - 해당 함수는 플레이 타임이 아닌, 현재가 하루의 몇 시인지 나타내는 함수입니다.

설명이 미흡한 부분은 연락 부탁드립니다.

**Comment by ruru14** [comment]
적절히 안정화가 되었으므로 이슈 클로징 하겠습니다.
